name: Automate PR
on:
  issues:
    types:
      - labeled

permissions:
  contents: read

jobs:
  Automate:
    if: github.event.label.name == 'Automate'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: write
    
    steps:
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          repository: step-security/secure-workflows
    
      - name: Automate PR
        uses: step-security/secure-workflows/Automate-PR@98ff385ea512d8ac7a1445f95e199f6864f439e1
        with:
          github-token: ${{secrets.PAT }}
          issue-id: ${{ github.event.issue.number}}