name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main # to update code coverage

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read
concurrency:
  group: ${{ github.workflow }}
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v1
        with:
          allowed-endpoints: >
            api.github.com:443
            codecov.io:443
            uploader.codecov.io:443
            github.com:443
            proxy.golang.org:443
            sum.golang.org:443
            storage.googleapis.com:443
            objects.githubusercontent.com:443
            golang.org:443
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.17
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
      - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2
